### ISSUE TITLE
Support long click

### ISSUE THREAD

**Issue by dbof10** [tikivn/NoAdapter#3]
I'm uisng `Nodatabinding` version. There is no way to use `LongClick`. There's even no method such as `ExtraBinding`. I think the field  `Item` in ViewHolder should be `protected` than `private`

**Comment by krongnang** [comment]
We have ExtraBinding,
you can bind your own any click event if needed @dbof10

**Comment by dbof10** [comment]
ok. Now I don't use this lib any more 👯‍♂
